name: Review Assign

on:
  pull_request:
    types: [opened, edited]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Action
        uses: hkusu/review-assign-action@v1
        id: assign
        with:
          assignees: ${{ github.actor }}
          draft-keyword: wip
      - name: Result
        if: always()
        run: echo '${{ steps.assign.outputs.result }}'