name: Review Assign

on:
  pull_request:
    types: [opened, unassigned]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Action
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}